# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zyxwvu/work/xyhttpd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zyxwvu/work/xyhttpd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyxwvu/work/xyhttpd/CMakeFiles /home/zyxwvu/work/xyhttpd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zyxwvu/work/xyhttpd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xyhttpd

# Build rule for target.
xyhttpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xyhttpd
.PHONY : xyhttpd

# fast build rule for target.
xyhttpd/fast:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/build
.PHONY : xyhttpd/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/xyfiber.o: src/xyfiber.cpp.o

.PHONY : src/xyfiber.o

# target to build an object file
src/xyfiber.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyfiber.cpp.o
.PHONY : src/xyfiber.cpp.o

src/xyfiber.i: src/xyfiber.cpp.i

.PHONY : src/xyfiber.i

# target to preprocess a source file
src/xyfiber.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyfiber.cpp.i
.PHONY : src/xyfiber.cpp.i

src/xyfiber.s: src/xyfiber.cpp.s

.PHONY : src/xyfiber.s

# target to generate assembly for a file
src/xyfiber.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyfiber.cpp.s
.PHONY : src/xyfiber.cpp.s

src/xyhttp.o: src/xyhttp.cpp.o

.PHONY : src/xyhttp.o

# target to build an object file
src/xyhttp.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttp.cpp.o
.PHONY : src/xyhttp.cpp.o

src/xyhttp.i: src/xyhttp.cpp.i

.PHONY : src/xyhttp.i

# target to preprocess a source file
src/xyhttp.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttp.cpp.i
.PHONY : src/xyhttp.cpp.i

src/xyhttp.s: src/xyhttp.cpp.s

.PHONY : src/xyhttp.s

# target to generate assembly for a file
src/xyhttp.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttp.cpp.s
.PHONY : src/xyhttp.cpp.s

src/xyhttpapi.o: src/xyhttpapi.cpp.o

.PHONY : src/xyhttpapi.o

# target to build an object file
src/xyhttpapi.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpapi.cpp.o
.PHONY : src/xyhttpapi.cpp.o

src/xyhttpapi.i: src/xyhttpapi.cpp.i

.PHONY : src/xyhttpapi.i

# target to preprocess a source file
src/xyhttpapi.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpapi.cpp.i
.PHONY : src/xyhttpapi.cpp.i

src/xyhttpapi.s: src/xyhttpapi.cpp.s

.PHONY : src/xyhttpapi.s

# target to generate assembly for a file
src/xyhttpapi.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpapi.cpp.s
.PHONY : src/xyhttpapi.cpp.s

src/xyhttprequest.o: src/xyhttprequest.cpp.o

.PHONY : src/xyhttprequest.o

# target to build an object file
src/xyhttprequest.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttprequest.cpp.o
.PHONY : src/xyhttprequest.cpp.o

src/xyhttprequest.i: src/xyhttprequest.cpp.i

.PHONY : src/xyhttprequest.i

# target to preprocess a source file
src/xyhttprequest.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttprequest.cpp.i
.PHONY : src/xyhttprequest.cpp.i

src/xyhttprequest.s: src/xyhttprequest.cpp.s

.PHONY : src/xyhttprequest.s

# target to generate assembly for a file
src/xyhttprequest.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttprequest.cpp.s
.PHONY : src/xyhttprequest.cpp.s

src/xyhttpresp.o: src/xyhttpresp.cpp.o

.PHONY : src/xyhttpresp.o

# target to build an object file
src/xyhttpresp.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpresp.cpp.o
.PHONY : src/xyhttpresp.cpp.o

src/xyhttpresp.i: src/xyhttpresp.cpp.i

.PHONY : src/xyhttpresp.i

# target to preprocess a source file
src/xyhttpresp.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpresp.cpp.i
.PHONY : src/xyhttpresp.cpp.i

src/xyhttpresp.s: src/xyhttpresp.cpp.s

.PHONY : src/xyhttpresp.s

# target to generate assembly for a file
src/xyhttpresp.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xyhttpresp.cpp.s
.PHONY : src/xyhttpresp.cpp.s

src/xylog.o: src/xylog.cpp.o

.PHONY : src/xylog.o

# target to build an object file
src/xylog.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xylog.cpp.o
.PHONY : src/xylog.cpp.o

src/xylog.i: src/xylog.cpp.i

.PHONY : src/xylog.i

# target to preprocess a source file
src/xylog.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xylog.cpp.i
.PHONY : src/xylog.cpp.i

src/xylog.s: src/xylog.cpp.s

.PHONY : src/xylog.s

# target to generate assembly for a file
src/xylog.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xylog.cpp.s
.PHONY : src/xylog.cpp.s

src/xystream.o: src/xystream.cpp.o

.PHONY : src/xystream.o

# target to build an object file
src/xystream.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystream.cpp.o
.PHONY : src/xystream.cpp.o

src/xystream.i: src/xystream.cpp.i

.PHONY : src/xystream.i

# target to preprocess a source file
src/xystream.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystream.cpp.i
.PHONY : src/xystream.cpp.i

src/xystream.s: src/xystream.cpp.s

.PHONY : src/xystream.s

# target to generate assembly for a file
src/xystream.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystream.cpp.s
.PHONY : src/xystream.cpp.s

src/xystreambuffer.o: src/xystreambuffer.cpp.o

.PHONY : src/xystreambuffer.o

# target to build an object file
src/xystreambuffer.cpp.o:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystreambuffer.cpp.o
.PHONY : src/xystreambuffer.cpp.o

src/xystreambuffer.i: src/xystreambuffer.cpp.i

.PHONY : src/xystreambuffer.i

# target to preprocess a source file
src/xystreambuffer.cpp.i:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystreambuffer.cpp.i
.PHONY : src/xystreambuffer.cpp.i

src/xystreambuffer.s: src/xystreambuffer.cpp.s

.PHONY : src/xystreambuffer.s

# target to generate assembly for a file
src/xystreambuffer.cpp.s:
	$(MAKE) -f CMakeFiles/xyhttpd.dir/build.make CMakeFiles/xyhttpd.dir/src/xystreambuffer.cpp.s
.PHONY : src/xystreambuffer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... xyhttpd"
	@echo "... edit_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/xyfiber.o"
	@echo "... src/xyfiber.i"
	@echo "... src/xyfiber.s"
	@echo "... src/xyhttp.o"
	@echo "... src/xyhttp.i"
	@echo "... src/xyhttp.s"
	@echo "... src/xyhttpapi.o"
	@echo "... src/xyhttpapi.i"
	@echo "... src/xyhttpapi.s"
	@echo "... src/xyhttprequest.o"
	@echo "... src/xyhttprequest.i"
	@echo "... src/xyhttprequest.s"
	@echo "... src/xyhttpresp.o"
	@echo "... src/xyhttpresp.i"
	@echo "... src/xyhttpresp.s"
	@echo "... src/xylog.o"
	@echo "... src/xylog.i"
	@echo "... src/xylog.s"
	@echo "... src/xystream.o"
	@echo "... src/xystream.i"
	@echo "... src/xystream.s"
	@echo "... src/xystreambuffer.o"
	@echo "... src/xystreambuffer.i"
	@echo "... src/xystreambuffer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

